pipeline{
  agent none
  stages{
    stage('Backend'){
      agent{
        docker { image 'maven'}
      }
    steps{ 
      sh 'mvn --version'
    }
    }
    stage('frontend'){
      agent{
        docker{ image 'node:16-alpine'}
      }
      steps{
        sh ' node --version'
      }
    }
     stage('db'){
      agent{
        docker{ image 'mysql'}
      }
      steps{
        sh ' mysql -V'
      }
    }
    stage('msg'){
      agent any
      steps{
        sh 'echo hello dosto'
      }
    }
   
  }
}
    
