pipeline{
  agent none
  stages{
    stage('Backend'){
      agent{
        docker { image 'maven'}
      }
    steps{ 
      sh 'mvn --version'
    }
    }
    stage('frontend'){
      agent{
        docker{ image 'node:16-alpine'}
      }
      steps{
        sh ' node --version'
      }
    }
  }
}
    
